server:
  port: 8080

spring:
  thymeleaf:
    mode: LEGACYHTML5
  application:
    name: "my-first-spring-boot-application"
  datasource:
    url: jdbc:postgresql://localhost:5432/sample
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  http:
     encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    org.springframework: ERROR
    com.netcracker.denisik: DEBUG
  file: logs.txt